# coding: utf-8

# flake8: noqa

"""
    The Blue Alliance API v3

    # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.  # noqa: E501

    OpenAPI spec version: 3.04.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.tba_api import TBAApi
from swagger_client.api.district_api import DistrictApi
from swagger_client.api.event_api import EventApi
from swagger_client.api.list_api import ListApi
from swagger_client.api.match_api import MatchApi
from swagger_client.api.team_api import TeamApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.api_status import APIStatus
from swagger_client.models.api_status_app_version import APIStatusAppVersion
from swagger_client.models.award import Award
from swagger_client.models.award_recipient import AwardRecipient
from swagger_client.models.district_list import DistrictList
from swagger_client.models.district_ranking import DistrictRanking
from swagger_client.models.district_ranking_event_points import DistrictRankingEventPoints
from swagger_client.models.elimination_alliance import EliminationAlliance
from swagger_client.models.elimination_alliance_backup import EliminationAllianceBackup
from swagger_client.models.elimination_alliance_status import EliminationAllianceStatus
from swagger_client.models.event import Event
from swagger_client.models.event_district_points import EventDistrictPoints
from swagger_client.models.event_district_points_points import EventDistrictPointsPoints
from swagger_client.models.event_district_points_tiebreakers import EventDistrictPointsTiebreakers
from swagger_client.models.event_insights import EventInsights
from swagger_client.models.event_insights2016 import EventInsights2016
from swagger_client.models.event_insights2017 import EventInsights2017
from swagger_client.models.event_insights2018 import EventInsights2018
from swagger_client.models.event_op_rs import EventOPRs
from swagger_client.models.event_predictions import EventPredictions
from swagger_client.models.event_ranking import EventRanking
from swagger_client.models.event_ranking_extra_stats_info import EventRankingExtraStatsInfo
from swagger_client.models.event_ranking_rankings import EventRankingRankings
from swagger_client.models.event_ranking_sort_order_info import EventRankingSortOrderInfo
from swagger_client.models.event_simple import EventSimple
from swagger_client.models.match import Match
from swagger_client.models.match_alliance import MatchAlliance
from swagger_client.models.match_score_breakdown2015 import MatchScoreBreakdown2015
from swagger_client.models.match_score_breakdown2015_alliance import MatchScoreBreakdown2015Alliance
from swagger_client.models.match_score_breakdown2016 import MatchScoreBreakdown2016
from swagger_client.models.match_score_breakdown2016_alliance import MatchScoreBreakdown2016Alliance
from swagger_client.models.match_score_breakdown2017 import MatchScoreBreakdown2017
from swagger_client.models.match_score_breakdown2017_alliance import MatchScoreBreakdown2017Alliance
from swagger_client.models.match_score_breakdown2018 import MatchScoreBreakdown2018
from swagger_client.models.match_score_breakdown2018_alliance import MatchScoreBreakdown2018Alliance
from swagger_client.models.match_score_breakdown2019 import MatchScoreBreakdown2019
from swagger_client.models.match_score_breakdown2019_alliance import MatchScoreBreakdown2019Alliance
from swagger_client.models.match_simple import MatchSimple
from swagger_client.models.match_simple_alliances import MatchSimpleAlliances
from swagger_client.models.match_timeseries2018 import MatchTimeseries2018
from swagger_client.models.match_videos import MatchVideos
from swagger_client.models.media import Media
from swagger_client.models.team import Team
from swagger_client.models.team_event_status import TeamEventStatus
from swagger_client.models.team_event_status_alliance import TeamEventStatusAlliance
from swagger_client.models.team_event_status_alliance_backup import TeamEventStatusAllianceBackup
from swagger_client.models.team_event_status_playoff import TeamEventStatusPlayoff
from swagger_client.models.team_event_status_rank import TeamEventStatusRank
from swagger_client.models.team_event_status_rank_ranking import TeamEventStatusRankRanking
from swagger_client.models.team_event_status_rank_sort_order_info import TeamEventStatusRankSortOrderInfo
from swagger_client.models.team_robot import TeamRobot
from swagger_client.models.team_simple import TeamSimple
from swagger_client.models.wlt_record import WLTRecord
from swagger_client.models.webcast import Webcast
